package frontend.ui.employee;

import com.toedter.calendar.JDateChooser;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.text.SimpleDateFormat;
import java.util.Comparator;
import java.util.Date;

/**
 * Represents the panel for managing attendance.
 * It provides functionality for clocking in and out, viewing attendance records,
 * searching for specific records, and resetting filters.
 * <p>
 * Available methods:
 * - {@link #enableSearch(boolean)}
 * - Getter methods for various components
 * <p>
 * Note: This class contains auto-generated code generated by the NetBeans GUI Builder.
 */

@SuppressWarnings({"unused", "FieldCanBeLocal", "MagicConstant", "FieldMayBeFinal"})
public class AttendancePanel extends javax.swing.JPanel {

    private DefaultTableModel attendanceTableModel;
    private TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form AttendancePanel
     */
    public AttendancePanel() {
        initComponents();
        initTable();

        enableSearch(false);

        // Update the clock every second
        Timer timer = new Timer(1000, e -> initTimeAndDate());
        timer.start();
    }

    //Getter methods to modify components

    /**
     * Enable or disable the search functionality.
     *
     * @param enabled true to enable search, false to disable
     */
    public void enableSearch(boolean enabled) {
        searchTextField.setEnabled(enabled);
        searchBTN.setEnabled(enabled);

        searchBTN.setVisible(enabled);
        searchTextField.setVisible(enabled);
    }


    // Custom Comparator for sorting dates in column 0
    private static class DateComparator implements Comparator<Object> {
        @Override
        public int compare(Object o1, Object o2) {
            String date1 = o1.toString();
            String date2 = o2.toString();
            return date2.compareTo(date1); // Sort in descending order (newest to oldest)
        }
    }

    /**
     * Initializes the time and date labels with the current time and date.
     */
    private void initTimeAndDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String currentTime = sdf.format(new Date());
        timeLabel.setText(currentTime);

        SimpleDateFormat sdf2 = new SimpleDateFormat("MMM/dd/yyyy");
        String currentDate = sdf2.format(new Date());
        String dayOfWeek = new SimpleDateFormat("EEEE").format(new Date());
        dateLabel.setText(dayOfWeek.toUpperCase() + ", " + currentDate);
    }


    /**
     * Initializes the table by setting up the table model, sorter, and setting the model for the attendance table.
     */
    private void initTable() {
        attendanceTableModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{
                },
                new String[]{
                        "Attendance ID", "Date", "Employee ID", "Last Name", "First Name", "Time In", "Time Out", "Overtime Hours", "Hours Worked"
                }
        ) {
            final boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        sorter = new TableRowSorter<>(attendanceTableModel);

        attendanceTable.setRowSorter(sorter);

        attendanceTable.setModel(attendanceTableModel);
    }

    /**
     * Retrieves the attendance table model.
     *
     * @return the attendance table model
     */
    public DefaultTableModel getAttendanceTableModel() {
        return attendanceTableModel;
    }

    /**
     * Gets the clock in button.
     *
     * @return the clock in button
     */
    public JButton getClockInBTN() {
        return clockInBTN;
    }

    /**
     * Retrieves the clock out button.
     *
     * @return the clock out button
     */
    public JButton getClockOutBTN() {
        return clockOutBTN;
    }

    /**
     * Get the attendance table.
     *
     * @return the attendance table
     */
    public JTable getAttendanceTable() {
        return attendanceTable;
    }

    /**
     * Get the attendance date chooser.
     *
     * @return the attendance date chooser
     */
    public JDateChooser getAttendanceDateChooser() {
        return attendanceDateChooser;
    }

    /**
     * Gets the attendance sorter for the table.
     *
     * @return the sorter for the attendance table
     */
    public TableRowSorter<DefaultTableModel> getAttendanceSorter() {
        return sorter;
    }

    /**
     * Gets the reset button.
     *
     * @return the reset button
     */
    public JButton getResetBTN() {
        return resetBTN;
    }

    /**
     * Gets the search button.
     *
     * @return the search button
     */
    public JButton getSearchBTN() {
        return searchBTN;
    }

    /**
     * Gets the search text field.
     *
     * @return the search text field
     */
    public JTextField getSearchTextField() {
        return searchTextField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        clockInBTN = new javax.swing.JButton();
        clockOutBTN = new javax.swing.JButton();
        attendanceDateChooser = new com.toedter.calendar.JDateChooser();
        searchTextField = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        myPayslipLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        resetBTN = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(244, 245, 247));
        setMinimumSize(new java.awt.Dimension(1135, 700));
        setPreferredSize(new java.awt.Dimension(1135, 700));
        setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMaximumSize(new java.awt.Dimension(550, 500));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(550, 500));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(550, 500));

        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String[]{
                        "Date", "Time In", "Time Out", "Overtime Hours", "Hours Worked"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(attendanceTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 50, 15, 50);
        add(jScrollPane2, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 50, 0, 0);
        add(jLabel2, gridBagConstraints);

        clockInBTN.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        clockInBTN.setText("Clock In");
        clockInBTN.setActionCommand("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 79, 0);
        add(clockInBTN, gridBagConstraints);

        clockOutBTN.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        clockOutBTN.setText("Clock Out");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 79, 0);
        add(clockOutBTN, gridBagConstraints);

        attendanceDateChooser.setMinimumSize(new java.awt.Dimension(200, 30));
        attendanceDateChooser.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 50, 0, 0);
        add(attendanceDateChooser, gridBagConstraints);

        searchTextField.setToolTipText("Employee ID");
        searchTextField.setMinimumSize(new java.awt.Dimension(200, 30));
        searchTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(searchTextField, gridBagConstraints);

        searchBTN.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        searchBTN.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        add(searchBTN, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        myPayslipLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        myPayslipLabel.setText("TIMESHEET");
        myPayslipLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        myPayslipLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        myPayslipLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 50, 34, 0);
        jPanel1.add(myPayslipLabel, gridBagConstraints);

        timeLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        timeLabel.setText("TIME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.4;
        jPanel1.add(timeLabel, gridBagConstraints);

        dateLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        dateLabel.setText("DATE");
        dateLabel.setMinimumSize(new java.awt.Dimension(250, 23));
        dateLabel.setPreferredSize(new java.awt.Dimension(250, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        jPanel1.add(dateLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel1, gridBagConstraints);

        resetBTN.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        resetBTN.setText("Reset");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 19);
        add(resetBTN, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser attendanceDateChooser;
    private javax.swing.JTable attendanceTable;
    private javax.swing.JButton clockInBTN;
    private javax.swing.JButton clockOutBTN;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel myPayslipLabel;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
