package frontend.ui.employee;

import com.toedter.calendar.JDateChooser;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 * Represents the panel for requesting leave.
 * It allows employees to request different types of leave, specify start and end dates,
 * provide a reason for the leave, and submit the request.
 * <p>
 * Available methods:
 * - Getter methods for various components
 * <p>
 * Note: This class contains auto-generated code generated by the NetBeans GUI Builder.
 */
@SuppressWarnings({"unused", "FieldCanBeLocal", "MagicConstant", "FieldMayBeFinal"})

public class LeavePanel extends javax.swing.JPanel {

    private DefaultTableModel leaveHistoryModel;
    private TableRowSorter<DefaultTableModel> leaveHistoryTableSorter;

    /**
     * Creates new form LeavePanel
     */
    public LeavePanel() {
        initComponents();
        initTable();
    }

    /**
     * Initializes the leave history table with default table model and sorter.
     */
    private void initTable() {
        leaveHistoryModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                        "Leave ID", "Employee ID", "Request Date", "LeaveType", "Start Date", "End Date", "Duration", "Reason", "Status"
                }
        ) {
            final boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        leaveHistoryTableSorter = new TableRowSorter<>(leaveHistoryModel);

        leaveHistoryTable.setRowSorter(leaveHistoryTableSorter);

        leaveHistoryTable.setModel(leaveHistoryModel);
    }

    /**
     * Retrieves the leave history table model.
     *
     * @return The leave history table model.
     */
    public DefaultTableModel getLeaveHistoryModel() {
        return leaveHistoryModel;
    }

    /**
     * Retrieves the Submit button.
     *
     * @return The Submit button.
     */
    public JButton getSubmitBTN() {
        return submitBTN;
    }

    /**
     * Retrieves the leave type combo box.
     *
     * @return The leave type combo box.
     */
    public JComboBox<String> getLeaveTypeComboBox() {
        return leaveTypeComboBox;
    }

    /**
     * Retrieves the start date chooser.
     *
     * @return The start date chooser.
     */
    public JDateChooser getStartDateChooser() {
        return startDateChooser;
    }

    /**
     * Retrieves the end date chooser.
     *
     * @return The end date chooser.
     */
    public JDateChooser getEndDateChooser() {
        return endDateChooser;
    }

    /**
     * Retrieves the leave reasons text area.
     *
     * @return The leave reasons text area.
     */
    public JTextArea getLeaveReasonsTxtArea() {
        return leaveReasonsTxtArea;
    }

    /**
     * Retrieves the sick leave text field.
     *
     * @return The sick leave text field.
     */
    public JTextField getSickLeaveTxtField() {
        return sickLeaveTxtField;
    }

    /**
     * Retrieves the vacation leave text field.
     *
     * @return The vacation leave text field.
     */
    public JTextField getVacationLeaveTxtField() {
        return vaccationLeaveTxtField;
    }

    /**
     * Retrieves the paternal leave text field.
     *
     * @return The paternal leave text field.
     */
    public JTextField getPaternalLeaveTxtField() {
        return paternalLeaveTxtField;
    }

    /**
     * Retrieves the bereavement leave text field.
     *
     * @return The bereavement leave text field.
     */
    public JTextField getBereavementLeaveTxtField() {
        return bereavementLeaveTxtField;
    }

    /**
     * Retrieves the leave history table.
     *
     * @return The leave history table.
     */
    public JTable getLeaveHistoryTable() {
        return leaveHistoryTable;
    }

    /**
     * Retrieves the leave history table sorter.
     *
     * @return The leave history table sorter.
     */
    public TableRowSorter<DefaultTableModel> getLeaveHistoryTableSorter() {
        return leaveHistoryTableSorter;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        requestLeaveLabel = new javax.swing.JLabel();
        requestLeavePanel = new javax.swing.JPanel();
        leaveTypeLabel = new javax.swing.JLabel();
        leaveTypeComboBox = new javax.swing.JComboBox<>();
        startDateLabel = new javax.swing.JLabel();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        leaveReasonsTxtArea = new javax.swing.JTextArea();
        submitBTN = new javax.swing.JButton();
        leaveCreditsLabel = new javax.swing.JLabel();
        leaveCreditsPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sickLeaveTxtField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        vaccationLeaveTxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        paternalLeaveTxtField = new javax.swing.JTextField();
        bereavementLeaveTxtField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        leaveHistoryLabel = new javax.swing.JLabel();
        leaveHistoryPanel = new javax.swing.JScrollPane();
        leaveHistoryTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        myPayslipLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 245, 247));
        setMinimumSize(new java.awt.Dimension(1135, 700));
        setPreferredSize(new java.awt.Dimension(1135, 700));
        setLayout(new java.awt.GridBagLayout());

        requestLeaveLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        requestLeaveLabel.setText("Request Leave");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        add(requestLeaveLabel, gridBagConstraints);

        requestLeavePanel.setBackground(new java.awt.Color(255, 255, 255));
        requestLeavePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        requestLeavePanel.setMinimumSize(new java.awt.Dimension(900, 300));
        requestLeavePanel.setPreferredSize(new java.awt.Dimension(900, 300));
        requestLeavePanel.setLayout(new java.awt.GridBagLayout());

        leaveTypeLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        leaveTypeLabel.setText("Leave Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 21, 0, 0);
        requestLeavePanel.add(leaveTypeLabel, gridBagConstraints);

        leaveTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"SICK", "VACATION", "PATERNAL", "BEREAVEMENT"}));
        leaveTypeComboBox.setMinimumSize(new java.awt.Dimension(150, 30));
        leaveTypeComboBox.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 0, 0);
        requestLeavePanel.add(leaveTypeComboBox, gridBagConstraints);

        startDateLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        startDateLabel.setText("Start date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 50, 0, 0);
        requestLeavePanel.add(startDateLabel, gridBagConstraints);

        endDateChooser.setMinimumSize(new java.awt.Dimension(200, 30));
        endDateChooser.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 50, 0, 20);
        requestLeavePanel.add(endDateChooser, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel9.setText("End date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 50, 0, 0);
        requestLeavePanel.add(jLabel9, gridBagConstraints);

        startDateChooser.setMinimumSize(new java.awt.Dimension(200, 30));
        startDateChooser.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 50, 0, 0);
        requestLeavePanel.add(startDateChooser, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel10.setText("Reason:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 21, 0, 0);
        requestLeavePanel.add(jLabel10, gridBagConstraints);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setMinimumSize(new java.awt.Dimension(234, 75));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(234, 75));

        leaveReasonsTxtArea.setColumns(20);
        leaveReasonsTxtArea.setRows(5);
        leaveReasonsTxtArea.setMinimumSize(new java.awt.Dimension(234, 75));
        leaveReasonsTxtArea.setPreferredSize(new java.awt.Dimension(234, 75));
        jScrollPane5.setViewportView(leaveReasonsTxtArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 318;
        gridBagConstraints.ipady = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 20, 0, 20);
        requestLeavePanel.add(jScrollPane5, gridBagConstraints);

        submitBTN.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        submitBTN.setText("Submit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 21, 16, 0);
        requestLeavePanel.add(submitBTN, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(17, 50, 28, 17);
        add(requestLeavePanel, gridBagConstraints);

        leaveCreditsLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        leaveCreditsLabel.setText("Leave Credits");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        add(leaveCreditsLabel, gridBagConstraints);

        leaveCreditsPanel.setBackground(new java.awt.Color(255, 255, 255));
        leaveCreditsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        leaveCreditsPanel.setMinimumSize(new java.awt.Dimension(285, 300));
        leaveCreditsPanel.setName(""); // NOI18N
        leaveCreditsPanel.setPreferredSize(new java.awt.Dimension(285, 300));
        leaveCreditsPanel.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel11.setText("Sick Leaves:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        leaveCreditsPanel.add(jLabel11, gridBagConstraints);

        sickLeaveTxtField.setMinimumSize(new java.awt.Dimension(200, 30));
        sickLeaveTxtField.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        leaveCreditsPanel.add(sickLeaveTxtField, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel12.setText("Vacation Leaves:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        leaveCreditsPanel.add(jLabel12, gridBagConstraints);

        vaccationLeaveTxtField.setMinimumSize(new java.awt.Dimension(200, 30));
        vaccationLeaveTxtField.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        leaveCreditsPanel.add(vaccationLeaveTxtField, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel13.setText("Paternal Leaves:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        leaveCreditsPanel.add(jLabel13, gridBagConstraints);

        paternalLeaveTxtField.setMinimumSize(new java.awt.Dimension(200, 30));
        paternalLeaveTxtField.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        leaveCreditsPanel.add(paternalLeaveTxtField, gridBagConstraints);

        bereavementLeaveTxtField.setMinimumSize(new java.awt.Dimension(200, 30));
        bereavementLeaveTxtField.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        leaveCreditsPanel.add(bereavementLeaveTxtField, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel14.setText("Bereavement Leaves:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        leaveCreditsPanel.add(jLabel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 28, 50);
        add(leaveCreditsPanel, gridBagConstraints);

        leaveHistoryLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        leaveHistoryLabel.setText("History");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 50, 0, 0);
        add(leaveHistoryLabel, gridBagConstraints);

        leaveHistoryPanel.setMinimumSize(new java.awt.Dimension(452, 350));
        leaveHistoryPanel.setPreferredSize(new java.awt.Dimension(452, 350));

        leaveHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{

                }
        ));
        leaveHistoryTable.setMaximumSize(new java.awt.Dimension(300, 80));
        leaveHistoryTable.setMinimumSize(new java.awt.Dimension(300, 350));
        leaveHistoryTable.setPreferredSize(new java.awt.Dimension(300, 350));
        leaveHistoryPanel.setViewportView(leaveHistoryTable);
        if (leaveHistoryTable.getColumnModel().getColumnCount() > 0) {
            leaveHistoryTable.getColumnModel().getColumn(1).setResizable(false);
            leaveHistoryTable.getColumnModel().getColumn(2).setResizable(false);
            leaveHistoryTable.getColumnModel().getColumn(3).setResizable(false);
            leaveHistoryTable.getColumnModel().getColumn(4).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 50, 15, 50);
        add(leaveHistoryPanel, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        myPayslipLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        myPayslipLabel.setText("LEAVE");
        myPayslipLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        myPayslipLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        myPayslipLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(36, 50, 34, 19);
        jPanel1.add(myPayslipLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bereavementLeaveTxtField;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel leaveCreditsLabel;
    private javax.swing.JPanel leaveCreditsPanel;
    private javax.swing.JLabel leaveHistoryLabel;
    private javax.swing.JScrollPane leaveHistoryPanel;
    private javax.swing.JTable leaveHistoryTable;
    private javax.swing.JTextArea leaveReasonsTxtArea;
    private javax.swing.JComboBox<String> leaveTypeComboBox;
    private javax.swing.JLabel leaveTypeLabel;
    private javax.swing.JLabel myPayslipLabel;
    private javax.swing.JTextField paternalLeaveTxtField;
    private javax.swing.JLabel requestLeaveLabel;
    private javax.swing.JPanel requestLeavePanel;
    private javax.swing.JTextField sickLeaveTxtField;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JButton submitBTN;
    private javax.swing.JTextField vaccationLeaveTxtField;
    // End of variables declaration//GEN-END:variables
}