package ui.employee;

import javax.swing.*;
import java.awt.*;

/**
 * Represents the panel for viewing employee profile information.
 * It provides access to various fields such as personal details, allowances, and identification numbers.
 * Available methods:
 * - Getter methods for accessing and modifying individual components
 * Note: This class contains auto-generated code generated by the NetBeans GUI Builder.
 */

@SuppressWarnings({"unused", "FieldCanBeLocal", "FieldMayBeFinal", "DataFlowIssue"})

public class MyProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form MyProfilePanel
     */
    public MyProfilePanel() {
        initComponents();
    }

    //Getter methods to allow editing of components


    /**
     * Retrieves the PhilHealth number text field.
     *
     * @return The PhilHealth number text field.
     */
    public JTextField philHealthNoTxtField() {
        return philHealthNoTxtField;
    }

    /**
     * Retrieves the basic salary text field.
     *
     * @return The basic salary text field.
     */
    public JTextField basicSalaryTxtField() {
        return basicSalaryTxtField;
    }

    /**
     * Retrieves the birthday text field.
     *
     * @return The birthday text field.
     */
    public JTextField birthdayTxtField() {
        return birthdayTxtField;
    }

    /**
     * Retrieves the clothing allowance text field.
     *
     * @return The clothing allowance text field.
     */
    public JTextField clothingAllowanceTxtField() {
        return clothingAllowanceTxtField;
    }

    /**
     * Retrieves the department text field.
     *
     * @return The department text field.
     */
    public JTextField departmentTxtField() {
        return departmentTxtField;
    }

    /**
     * Retrieves the employee ID text field.
     *
     * @return The employee ID text field.
     */
    public JTextField empIDTxtField() {
        return empIDTxtField;
    }

    /**
     * Retrieves the hourly rate text field.
     *
     * @return The hourly rate text field.
     */
    public JTextField hourlyRateTxtField() {
        return hourlyRateTxtField;
    }

    /**
     * Retrieves the name text field.
     *
     * @return The name text field.
     */
    public JTextField nameTxtField() {
        return nameTxtField;
    }

    /**
     * Retrieves the PagIbig number text field.
     *
     * @return The PagIbig number text field.
     */
    public JTextField pagIbigNoTxtField() {
        return pagIbigNoTxtField;
    }

    /**
     * Retrieves the phone allowance text field.
     *
     * @return The phone allowance text field.
     */
    public JTextField phoneAllowanceTxtField() {
        return phoneAllowanceTxtField;
    }

    /**
     * Retrieves the phone number text field.
     *
     * @return The phone number text field.
     */
    public JTextField phoneNoTxtField() {
        return phoneNoTxtField;
    }

    /**
     * Retrieves the position text field.
     *
     * @return The position text field.
     */
    public JTextField positionTxtField() {
        return positionTxtField;
    }

    /**
     * Retrieves the rice subsidy text field.
     *
     * @return The rice subsidy text field.
     */
    public JTextField riceSubsidyTxtField() {
        return riceSubsidyTxtField;
    }

    /**
     * Retrieves the semi-monthly text field.
     *
     * @return The semi-monthly text field.
     */
    public JTextField semiMonthlyTxtField() {
        return semiMonthlyTxtField;
    }

    /**
     * Retrieves the status text field.
     *
     * @return The status text field.
     */
    public JTextField statusTxtField() {
        return statusTxtField;
    }

    /**
     * Retrieves the supervisor text field.
     *
     * @return The supervisor text field.
     */
    public JTextField supervisorTxtField() {
        return supervisorTxtField;
    }

    /**
     * Retrieves the SSS number text field.
     *
     * @return The SSS number text field.
     */
    public JTextField sssNoTextField() {
        return sssNoTextField;
    }

    /**
     * Retrieves the TIN number text field.
     *
     * @return The TIN number text field.
     */
    public JTextField tinNoTxtField() {
        return tinNoTxtField;
    }

    /**
     * Retrieves the address text field.
     *
     * @return The address text field.
     */
    public JTextField addressTxtField() {
        return addressTxtField;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JPanel personalPanel = new JPanel();
        JLabel nameLabel = new JLabel();
        nameTxtField = new javax.swing.JTextField();
        JLabel birthdayLabel = new JLabel();
        birthdayTxtField = new javax.swing.JTextField();
        JLabel phoneNoLabel = new JLabel();
        addressTxtField = new javax.swing.JTextField();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JLabel addressLabel = new JLabel();
        phoneNoTxtField = new javax.swing.JTextField();
        JPanel jPanel1 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JPanel employmentPanel = new JPanel();
        JLabel empIDLabel = new JLabel();
        empIDTxtField = new javax.swing.JTextField();
        JLabel departmentLabel = new JLabel();
        departmentTxtField = new javax.swing.JTextField();
        JLabel positionLabel = new JLabel();
        positionTxtField = new javax.swing.JTextField();
        JLabel supervisorLabel = new JLabel();
        supervisorTxtField = new javax.swing.JTextField();
        JLabel statusLabel = new JLabel();
        statusTxtField = new javax.swing.JTextField();
        JLabel payLabel1 = new JLabel();
        JPanel payPanel = new JPanel();
        JLabel basicSalaryLabel = new JLabel();
        basicSalaryTxtField = new javax.swing.JTextField();
        JLabel hourlyRateLabel = new JLabel();
        hourlyRateTxtField = new javax.swing.JTextField();
        JLabel semiMonthlyLabel = new JLabel();
        semiMonthlyTxtField = new javax.swing.JTextField();
        JLabel payLabel = new JLabel();
        JPanel jPanel3 = new JPanel();
        JLabel riceSubsidyLabel = new JLabel();
        riceSubsidyTxtField = new javax.swing.JTextField();
        JLabel phoneAllowanceLabel = new JLabel();
        JLabel clothingAllowanceLabel = new JLabel();
        clothingAllowanceTxtField = new javax.swing.JTextField();
        phoneAllowanceTxtField = new javax.swing.JTextField();
        JLabel allowancesLabel = new JLabel();
        JPanel jPanel4 = new JPanel();
        JLabel sssNoLabel = new JLabel();
        sssNoTextField = new javax.swing.JTextField();
        JLabel philHealthNoLabel = new JLabel();
        philHealthNoTxtField = new javax.swing.JTextField();
        JLabel pagIbigNoLabel = new JLabel();
        pagIbigNoTxtField = new javax.swing.JTextField();
        tinNoTxtField = new javax.swing.JTextField();
        JLabel tinNoLabel = new JLabel();
        JLabel contributionIDsLabel = new JLabel();

        setBackground(new java.awt.Color(244, 245, 247));
        setMinimumSize(new java.awt.Dimension(1135, 700));
        setPreferredSize(new java.awt.Dimension(1135, 700));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[]{0, 0, 0, 0, 0};
        layout.rowHeights = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0};
        setLayout(layout);

        personalPanel.setBackground(new java.awt.Color(249, 249, 249));
        personalPanel.setMinimumSize(new java.awt.Dimension(10, 185));
        personalPanel.setPreferredSize(new java.awt.Dimension(10, 185));
        personalPanel.setLayout(new java.awt.GridBagLayout());

        nameLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        nameLabel.setText("NAME");
        nameLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        nameLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        personalPanel.add(nameLabel, gridBagConstraints);

        nameTxtField.setEditable(false);
        nameTxtField.setBackground(personalPanel.getBackground());
        nameTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        nameTxtField.setBorder(null);
        nameTxtField.setMinimumSize(new java.awt.Dimension(350, 20));
        nameTxtField.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 0);
        personalPanel.add(nameTxtField, gridBagConstraints);

        birthdayLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        birthdayLabel.setText("DOB");
        birthdayLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        birthdayLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        personalPanel.add(birthdayLabel, gridBagConstraints);

        birthdayTxtField.setEditable(false);
        birthdayTxtField.setBackground(personalPanel.getBackground());
        birthdayTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        birthdayTxtField.setBorder(null);
        birthdayTxtField.setMinimumSize(new java.awt.Dimension(350, 20));
        birthdayTxtField.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 0);
        personalPanel.add(birthdayTxtField, gridBagConstraints);

        phoneNoLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        phoneNoLabel.setText("PHONE NO");
        phoneNoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        phoneNoLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        personalPanel.add(phoneNoLabel, gridBagConstraints);

        addressTxtField.setEditable(false);
        addressTxtField.setBackground(personalPanel.getBackground());
        addressTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        addressTxtField.setBorder(null);
        addressTxtField.setMinimumSize(new java.awt.Dimension(350, 20));
        addressTxtField.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 0);
        personalPanel.add(addressTxtField, gridBagConstraints);

        addressLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        addressLabel.setText("ADDRESS");
        addressLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        addressLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        personalPanel.add(addressLabel, gridBagConstraints);

        phoneNoTxtField.setEditable(false);
        phoneNoTxtField.setBackground(personalPanel.getBackground());
        phoneNoTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        phoneNoTxtField.setBorder(null);
        phoneNoTxtField.setMinimumSize(new java.awt.Dimension(350, 20));
        phoneNoTxtField.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 0);
        personalPanel.add(phoneNoTxtField, gridBagConstraints);

        jPanel1.setBackground(personalPanel.getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(125, 125));
        jPanel1.setPreferredSize(new java.awt.Dimension(125, 125));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/userIcon.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        personalPanel.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        add(personalPanel, gridBagConstraints);

        employmentPanel.setBackground(new java.awt.Color(249, 249, 249));
        employmentPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(249, 249, 249), new java.awt.Color(102, 102, 102)));
        employmentPanel.setMinimumSize(new java.awt.Dimension(533, 220));
        employmentPanel.setPreferredSize(new java.awt.Dimension(533, 220));
        employmentPanel.setLayout(new java.awt.GridBagLayout());

        empIDLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        empIDLabel.setText("EMPLOYEE ID");
        empIDLabel.setMinimumSize(new java.awt.Dimension(200, 15));
        empIDLabel.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(empIDLabel, gridBagConstraints);

        empIDTxtField.setEditable(false);
        empIDTxtField.setBackground(personalPanel.getBackground());
        empIDTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        empIDTxtField.setBorder(null);
        empIDTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        empIDTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(empIDTxtField, gridBagConstraints);

        departmentLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        departmentLabel.setText("DEPARTMENT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(departmentLabel, gridBagConstraints);

        departmentTxtField.setEditable(false);
        departmentTxtField.setBackground(personalPanel.getBackground());
        departmentTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        departmentTxtField.setBorder(null);
        departmentTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        departmentTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(departmentTxtField, gridBagConstraints);

        positionLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        positionLabel.setText("POSITION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(positionLabel, gridBagConstraints);

        positionTxtField.setEditable(false);
        positionTxtField.setBackground(personalPanel.getBackground());
        positionTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        positionTxtField.setBorder(null);
        positionTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        positionTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(positionTxtField, gridBagConstraints);

        supervisorLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        supervisorLabel.setText("SUPERVISOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(supervisorLabel, gridBagConstraints);

        supervisorTxtField.setEditable(false);
        supervisorTxtField.setBackground(personalPanel.getBackground());
        supervisorTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        supervisorTxtField.setBorder(null);
        supervisorTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        supervisorTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(supervisorTxtField, gridBagConstraints);

        statusLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        statusLabel.setText("STATUS ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(statusLabel, gridBagConstraints);

        statusTxtField.setEditable(false);
        statusTxtField.setBackground(personalPanel.getBackground());
        statusTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        statusTxtField.setBorder(null);
        statusTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        statusTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(statusTxtField, gridBagConstraints);

        payLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", Font.PLAIN, 18)); // NOI18N
        payLabel1.setText("Employment");
        payLabel1.setMinimumSize(new java.awt.Dimension(250, 25));
        payLabel1.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        employmentPanel.add(payLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 18, 16);
        add(employmentPanel, gridBagConstraints);

        payPanel.setBackground(new java.awt.Color(249, 249, 249));
        payPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(249, 249, 249), new java.awt.Color(102, 102, 102)));
        payPanel.setToolTipText("");
        payPanel.setMinimumSize(new java.awt.Dimension(533, 200));
        payPanel.setPreferredSize(new java.awt.Dimension(533, 200));
        payPanel.setLayout(new java.awt.GridBagLayout());

        basicSalaryLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        basicSalaryLabel.setText("BASIC SALARY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(basicSalaryLabel, gridBagConstraints);

        basicSalaryTxtField.setEditable(false);
        basicSalaryTxtField.setBackground(personalPanel.getBackground());
        basicSalaryTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        basicSalaryTxtField.setBorder(null);
        basicSalaryTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        basicSalaryTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(basicSalaryTxtField, gridBagConstraints);

        hourlyRateLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        hourlyRateLabel.setText("HOURLY RATE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(hourlyRateLabel, gridBagConstraints);

        hourlyRateTxtField.setEditable(false);
        hourlyRateTxtField.setBackground(personalPanel.getBackground());
        hourlyRateTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        hourlyRateTxtField.setBorder(null);
        hourlyRateTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        hourlyRateTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(hourlyRateTxtField, gridBagConstraints);

        semiMonthlyLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        semiMonthlyLabel.setText("SEMI-MONTHLY RATE");
        semiMonthlyLabel.setMinimumSize(new java.awt.Dimension(200, 15));
        semiMonthlyLabel.setPreferredSize(new java.awt.Dimension(150, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(semiMonthlyLabel, gridBagConstraints);

        semiMonthlyTxtField.setEditable(false);
        semiMonthlyTxtField.setBackground(personalPanel.getBackground());
        semiMonthlyTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        semiMonthlyTxtField.setBorder(null);
        semiMonthlyTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        semiMonthlyTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(semiMonthlyTxtField, gridBagConstraints);

        payLabel.setFont(new java.awt.Font("Montserrat ExtraBold", Font.PLAIN, 18)); // NOI18N
        payLabel.setText("Salary");
        payLabel.setMinimumSize(new java.awt.Dimension(250, 25));
        payLabel.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        payPanel.add(payLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 18, 16);
        add(payPanel, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(249, 249, 249), new java.awt.Color(102, 102, 102)));
        jPanel3.setMinimumSize(new java.awt.Dimension(533, 200));
        jPanel3.setPreferredSize(new java.awt.Dimension(533, 200));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        riceSubsidyLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        riceSubsidyLabel.setText("RICE SUBSIDY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(riceSubsidyLabel, gridBagConstraints);

        riceSubsidyTxtField.setEditable(false);
        riceSubsidyTxtField.setBackground(personalPanel.getBackground());
        riceSubsidyTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        riceSubsidyTxtField.setBorder(null);
        riceSubsidyTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        riceSubsidyTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(riceSubsidyTxtField, gridBagConstraints);

        phoneAllowanceLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        phoneAllowanceLabel.setText("PHONE ALLOWANCE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(phoneAllowanceLabel, gridBagConstraints);

        clothingAllowanceLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        clothingAllowanceLabel.setText("CLOTHING ALLOWANCE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(clothingAllowanceLabel, gridBagConstraints);

        clothingAllowanceTxtField.setEditable(false);
        clothingAllowanceTxtField.setBackground(personalPanel.getBackground());
        clothingAllowanceTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        clothingAllowanceTxtField.setBorder(null);
        clothingAllowanceTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        clothingAllowanceTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(clothingAllowanceTxtField, gridBagConstraints);

        phoneAllowanceTxtField.setEditable(false);
        phoneAllowanceTxtField.setBackground(personalPanel.getBackground());
        phoneAllowanceTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        phoneAllowanceTxtField.setBorder(null);
        phoneAllowanceTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        phoneAllowanceTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(phoneAllowanceTxtField, gridBagConstraints);

        allowancesLabel.setFont(new java.awt.Font("Montserrat ExtraBold", Font.PLAIN, 18)); // NOI18N
        allowancesLabel.setText("Allowances");
        allowancesLabel.setMinimumSize(new java.awt.Dimension(250, 25));
        allowancesLabel.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        jPanel3.add(allowancesLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 18, 50);
        add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(249, 249, 249), new java.awt.Color(102, 102, 102)));
        jPanel4.setMinimumSize(new java.awt.Dimension(533, 220));
        jPanel4.setPreferredSize(new java.awt.Dimension(533, 220));
        java.awt.GridBagLayout jPanel4Layout1 = new java.awt.GridBagLayout();
        jPanel4Layout1.columnWidths = new int[]{0, 0, 0};
        jPanel4Layout1.rowHeights = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanel4.setLayout(jPanel4Layout1);

        sssNoLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        sssNoLabel.setText("SSS NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        jPanel4.add(sssNoLabel, gridBagConstraints);

        sssNoTextField.setEditable(false);
        sssNoTextField.setBackground(personalPanel.getBackground());
        sssNoTextField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        sssNoTextField.setBorder(null);
        sssNoTextField.setMinimumSize(new java.awt.Dimension(250, 20));
        sssNoTextField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 63, 5, 0);
        jPanel4.add(sssNoTextField, gridBagConstraints);

        philHealthNoLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        philHealthNoLabel.setText("PHILHEALTH NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        jPanel4.add(philHealthNoLabel, gridBagConstraints);

        philHealthNoTxtField.setEditable(false);
        philHealthNoTxtField.setBackground(personalPanel.getBackground());
        philHealthNoTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        philHealthNoTxtField.setBorder(null);
        philHealthNoTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        philHealthNoTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 63, 5, 0);
        jPanel4.add(philHealthNoTxtField, gridBagConstraints);

        pagIbigNoLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        pagIbigNoLabel.setText("PAGIBIG NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        jPanel4.add(pagIbigNoLabel, gridBagConstraints);

        pagIbigNoTxtField.setEditable(false);
        pagIbigNoTxtField.setBackground(personalPanel.getBackground());
        pagIbigNoTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        pagIbigNoTxtField.setBorder(null);
        pagIbigNoTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        pagIbigNoTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 63, 5, 0);
        jPanel4.add(pagIbigNoTxtField, gridBagConstraints);

        tinNoTxtField.setEditable(false);
        tinNoTxtField.setBackground(personalPanel.getBackground());
        tinNoTxtField.setFont(new java.awt.Font("Montserrat Medium", Font.PLAIN, 12)); // NOI18N
        tinNoTxtField.setBorder(null);
        tinNoTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        tinNoTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 63, 5, 0);
        jPanel4.add(tinNoTxtField, gridBagConstraints);

        tinNoLabel.setFont(new java.awt.Font("Montserrat Medium", Font.BOLD, 12)); // NOI18N
        tinNoLabel.setText("TIN NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        jPanel4.add(tinNoLabel, gridBagConstraints);

        contributionIDsLabel.setFont(new java.awt.Font("Montserrat ExtraBold", Font.PLAIN, 18)); // NOI18N
        contributionIDsLabel.setText("Contribution ID's");
        contributionIDsLabel.setMinimumSize(new java.awt.Dimension(250, 25));
        contributionIDsLabel.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        jPanel4.add(contributionIDsLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 18, 50);
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JTextField addressTxtField;
    private javax.swing.JTextField basicSalaryTxtField;
    private javax.swing.JTextField birthdayTxtField;
    private javax.swing.JTextField clothingAllowanceTxtField;
    private javax.swing.JTextField departmentTxtField;
    private javax.swing.JTextField empIDTxtField;
    private javax.swing.JTextField hourlyRateTxtField;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTextField pagIbigNoTxtField;
    private javax.swing.JTextField philHealthNoTxtField;
    private javax.swing.JTextField phoneAllowanceTxtField;
    private javax.swing.JTextField phoneNoTxtField;
    private javax.swing.JTextField positionTxtField;
    private javax.swing.JTextField riceSubsidyTxtField;
    private javax.swing.JTextField semiMonthlyTxtField;
    private javax.swing.JTextField sssNoTextField;
    private javax.swing.JTextField statusTxtField;
    private javax.swing.JTextField supervisorTxtField;
    private javax.swing.JTextField tinNoTxtField;
    // End of variables declaration//GEN-END:variables
}
