/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.employee;

import javax.swing.*;

/**
 * @author Lenovo
 */
public class MyProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form MyProfilePanel
     */
    public MyProfilePanel() {
        initComponents();
    }

    //Getter methods to allow editing of components


    public JTextField philHealthNoTxtField() {
        return philHealthNoTxtField;
    }

    public JTextField basicSalaryTxtField() {
        return basicSalaryTxtField;
    }

    public JTextField birthdayTxtField() {
        return birthdayTxtField;
    }

    public JTextField clothingAllowanceTxtField() {
        return clothingAllowanceTxtField;
    }

    public JTextField departmentTxtField() {
        return departmentTxtField;
    }

    public JTextField empIDTxtField() {
        return empIDTxtField;
    }

    public JTextField hourlyRateTxtField() {
        return hourlyRateTxtField;
    }

    public JTextField nameTxtField() {
        return nameTxtField;
    }

    public JTextField pagIbigNoTxtField() {
        return pagibigNoTxtField;
    }

    public JTextField phoneAllowanceTxtField() {
        return phoneAllowanceTxtField;
    }

    public JTextField phoneNoTxtField() {
        return phoneNoTxtField;
    }

    public JTextField positionTxtField() {
        return positionTxtField;
    }

    public JTextField riceSubsidyTxtField() {
        return riceSubsidyTxtField;
    }

    public JTextField semiMonthlyTxtField() {
        return semiMonthlyTxtField;
    }

    public JTextField statusTxtField() {
        return statusTxtField;
    }

    public JTextField supervisoTxtField() {
        return supervisoTxtField;
    }

    public JTextField sssNoTextField() {
        return sssNoTextField;
    }

    public JTextField tinNoTxtField() {
        return tinNoTxtField;
    }

    public JTextField addressTxtField() {
        return addressTxtField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        personalPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        birthdayTxtField = new javax.swing.JTextField();
        phoneNoLabel = new javax.swing.JLabel();
        addressTxtField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        phoneNoTxtField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        employmentPanel = new javax.swing.JPanel();
        empIDLabel = new javax.swing.JLabel();
        empIDTxtField = new javax.swing.JTextField();
        departmentLabel = new javax.swing.JLabel();
        departmentTxtField = new javax.swing.JTextField();
        positionLabel = new javax.swing.JLabel();
        positionTxtField = new javax.swing.JTextField();
        supervisorLabel = new javax.swing.JLabel();
        supervisoTxtField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        statusTxtField = new javax.swing.JTextField();
        payLabel1 = new javax.swing.JLabel();
        payPanel = new javax.swing.JPanel();
        basicSalaryLabel = new javax.swing.JLabel();
        basicSalaryTxtField = new javax.swing.JTextField();
        hourlyRateLabel = new javax.swing.JLabel();
        hourlyRateTxtField = new javax.swing.JTextField();
        semiMonthlyLabel = new javax.swing.JLabel();
        semiMonthlyTxtField = new javax.swing.JTextField();
        payLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        riceSubsidyLabel = new javax.swing.JLabel();
        riceSubsidyTxtField = new javax.swing.JTextField();
        phoneAllowanceLabel = new javax.swing.JLabel();
        clothingAllowanceLabel = new javax.swing.JLabel();
        clothingAllowanceTxtField = new javax.swing.JTextField();
        phoneAllowanceTxtField = new javax.swing.JTextField();
        allowancesLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sssNoLabel = new javax.swing.JLabel();
        sssNoTextField = new javax.swing.JTextField();
        philhealthNoLabel = new javax.swing.JLabel();
        philHealthNoTxtField = new javax.swing.JTextField();
        pagibigNoLabel = new javax.swing.JLabel();
        pagibigNoTxtField = new javax.swing.JTextField();
        tinNoTxtField = new javax.swing.JTextField();
        tinNoLabel = new javax.swing.JLabel();
        contributionIDsLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 245, 247));
        setMinimumSize(new java.awt.Dimension(1135, 700));
        setPreferredSize(new java.awt.Dimension(1135, 700));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[]{0, 0, 0, 0, 0};
        layout.rowHeights = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0};
        setLayout(layout);

        personalPanel.setBackground(new java.awt.Color(249, 249, 249));
        personalPanel.setMinimumSize(new java.awt.Dimension(10, 185));
        personalPanel.setPreferredSize(new java.awt.Dimension(10, 185));
        personalPanel.setLayout(new java.awt.GridBagLayout());

        nameLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        nameLabel.setText("NAME");
        nameLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        nameLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        personalPanel.add(nameLabel, gridBagConstraints);

        nameTxtField.setEditable(false);
        nameTxtField.setBackground(personalPanel.getBackground());
        nameTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        nameTxtField.setBorder(null);
        nameTxtField.setMinimumSize(new java.awt.Dimension(350, 20));
        nameTxtField.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 0);
        personalPanel.add(nameTxtField, gridBagConstraints);

        birthdayLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        birthdayLabel.setText("DOB");
        birthdayLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        birthdayLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        personalPanel.add(birthdayLabel, gridBagConstraints);

        birthdayTxtField.setEditable(false);
        birthdayTxtField.setBackground(personalPanel.getBackground());
        birthdayTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        birthdayTxtField.setBorder(null);
        birthdayTxtField.setMinimumSize(new java.awt.Dimension(350, 20));
        birthdayTxtField.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 0);
        personalPanel.add(birthdayTxtField, gridBagConstraints);

        phoneNoLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        phoneNoLabel.setText("PHONE NO");
        phoneNoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        phoneNoLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        personalPanel.add(phoneNoLabel, gridBagConstraints);

        addressTxtField.setEditable(false);
        addressTxtField.setBackground(personalPanel.getBackground());
        addressTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        addressTxtField.setBorder(null);
        addressTxtField.setMinimumSize(new java.awt.Dimension(350, 20));
        addressTxtField.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 0);
        personalPanel.add(addressTxtField, gridBagConstraints);

        addressLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        addressLabel.setText("ADDRESS");
        addressLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        addressLabel.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        personalPanel.add(addressLabel, gridBagConstraints);

        phoneNoTxtField.setEditable(false);
        phoneNoTxtField.setBackground(personalPanel.getBackground());
        phoneNoTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        phoneNoTxtField.setBorder(null);
        phoneNoTxtField.setMinimumSize(new java.awt.Dimension(350, 20));
        phoneNoTxtField.setPreferredSize(new java.awt.Dimension(350, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 3, 4, 0);
        personalPanel.add(phoneNoTxtField, gridBagConstraints);

        jPanel1.setBackground(personalPanel.getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(125, 125));
        jPanel1.setPreferredSize(new java.awt.Dimension(125, 125));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/userIcon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        personalPanel.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        add(personalPanel, gridBagConstraints);

        employmentPanel.setBackground(new java.awt.Color(249, 249, 249));
        employmentPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(249, 249, 249), new java.awt.Color(102, 102, 102)));
        employmentPanel.setMinimumSize(new java.awt.Dimension(533, 220));
        employmentPanel.setPreferredSize(new java.awt.Dimension(533, 220));
        employmentPanel.setLayout(new java.awt.GridBagLayout());

        empIDLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        empIDLabel.setText("EMPLOYEE ID");
        empIDLabel.setMinimumSize(new java.awt.Dimension(200, 15));
        empIDLabel.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(empIDLabel, gridBagConstraints);

        empIDTxtField.setEditable(false);
        empIDTxtField.setBackground(personalPanel.getBackground());
        empIDTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        empIDTxtField.setBorder(null);
        empIDTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        empIDTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(empIDTxtField, gridBagConstraints);

        departmentLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        departmentLabel.setText("DEPARTMENT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(departmentLabel, gridBagConstraints);

        departmentTxtField.setEditable(false);
        departmentTxtField.setBackground(personalPanel.getBackground());
        departmentTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        departmentTxtField.setBorder(null);
        departmentTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        departmentTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(departmentTxtField, gridBagConstraints);

        positionLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        positionLabel.setText("POSITION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(positionLabel, gridBagConstraints);

        positionTxtField.setEditable(false);
        positionTxtField.setBackground(personalPanel.getBackground());
        positionTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        positionTxtField.setBorder(null);
        positionTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        positionTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(positionTxtField, gridBagConstraints);

        supervisorLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        supervisorLabel.setText("SUPERVISOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(supervisorLabel, gridBagConstraints);

        supervisoTxtField.setEditable(false);
        supervisoTxtField.setBackground(personalPanel.getBackground());
        supervisoTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        supervisoTxtField.setBorder(null);
        supervisoTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        supervisoTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(supervisoTxtField, gridBagConstraints);

        statusLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        statusLabel.setText("STATUS ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        employmentPanel.add(statusLabel, gridBagConstraints);

        statusTxtField.setEditable(false);
        statusTxtField.setBackground(personalPanel.getBackground());
        statusTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        statusTxtField.setBorder(null);
        statusTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        statusTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 74, 5, 0);
        employmentPanel.add(statusTxtField, gridBagConstraints);

        payLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        payLabel1.setText("Employment");
        payLabel1.setMinimumSize(new java.awt.Dimension(250, 25));
        payLabel1.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        employmentPanel.add(payLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 18, 16);
        add(employmentPanel, gridBagConstraints);

        payPanel.setBackground(new java.awt.Color(249, 249, 249));
        payPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(249, 249, 249), new java.awt.Color(102, 102, 102)));
        payPanel.setToolTipText("");
        payPanel.setMinimumSize(new java.awt.Dimension(533, 200));
        payPanel.setPreferredSize(new java.awt.Dimension(533, 200));
        payPanel.setLayout(new java.awt.GridBagLayout());

        basicSalaryLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        basicSalaryLabel.setText("BASIC SALARY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(basicSalaryLabel, gridBagConstraints);

        basicSalaryTxtField.setEditable(false);
        basicSalaryTxtField.setBackground(personalPanel.getBackground());
        basicSalaryTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        basicSalaryTxtField.setBorder(null);
        basicSalaryTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        basicSalaryTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(basicSalaryTxtField, gridBagConstraints);

        hourlyRateLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        hourlyRateLabel.setText("HOURLY RATE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(hourlyRateLabel, gridBagConstraints);

        hourlyRateTxtField.setEditable(false);
        hourlyRateTxtField.setBackground(personalPanel.getBackground());
        hourlyRateTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        hourlyRateTxtField.setBorder(null);
        hourlyRateTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        hourlyRateTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(hourlyRateTxtField, gridBagConstraints);

        semiMonthlyLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        semiMonthlyLabel.setText("SEMI-MONTHLY RATE");
        semiMonthlyLabel.setMinimumSize(new java.awt.Dimension(200, 15));
        semiMonthlyLabel.setPreferredSize(new java.awt.Dimension(150, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(semiMonthlyLabel, gridBagConstraints);

        semiMonthlyTxtField.setEditable(false);
        semiMonthlyTxtField.setBackground(personalPanel.getBackground());
        semiMonthlyTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        semiMonthlyTxtField.setBorder(null);
        semiMonthlyTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        semiMonthlyTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        payPanel.add(semiMonthlyTxtField, gridBagConstraints);

        payLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        payLabel.setText("Salary");
        payLabel.setMinimumSize(new java.awt.Dimension(250, 25));
        payLabel.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        payPanel.add(payLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 18, 16);
        add(payPanel, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(249, 249, 249), new java.awt.Color(102, 102, 102)));
        jPanel3.setMinimumSize(new java.awt.Dimension(533, 200));
        jPanel3.setPreferredSize(new java.awt.Dimension(533, 200));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        riceSubsidyLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        riceSubsidyLabel.setText("RICE SUBSIDY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(riceSubsidyLabel, gridBagConstraints);

        riceSubsidyTxtField.setEditable(false);
        riceSubsidyTxtField.setBackground(personalPanel.getBackground());
        riceSubsidyTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        riceSubsidyTxtField.setBorder(null);
        riceSubsidyTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        riceSubsidyTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(riceSubsidyTxtField, gridBagConstraints);

        phoneAllowanceLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        phoneAllowanceLabel.setText("PHONE ALLOWANCE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(phoneAllowanceLabel, gridBagConstraints);

        clothingAllowanceLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        clothingAllowanceLabel.setText("CLOTHING ALLOWANCE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(clothingAllowanceLabel, gridBagConstraints);

        clothingAllowanceTxtField.setEditable(false);
        clothingAllowanceTxtField.setBackground(personalPanel.getBackground());
        clothingAllowanceTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        clothingAllowanceTxtField.setBorder(null);
        clothingAllowanceTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        clothingAllowanceTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(clothingAllowanceTxtField, gridBagConstraints);

        phoneAllowanceTxtField.setEditable(false);
        phoneAllowanceTxtField.setBackground(personalPanel.getBackground());
        phoneAllowanceTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        phoneAllowanceTxtField.setBorder(null);
        phoneAllowanceTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        phoneAllowanceTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 0);
        jPanel3.add(phoneAllowanceTxtField, gridBagConstraints);

        allowancesLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        allowancesLabel.setText("Allowances");
        allowancesLabel.setMinimumSize(new java.awt.Dimension(250, 25));
        allowancesLabel.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        jPanel3.add(allowancesLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 18, 50);
        add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(249, 249, 249), new java.awt.Color(102, 102, 102)));
        jPanel4.setMinimumSize(new java.awt.Dimension(533, 220));
        jPanel4.setPreferredSize(new java.awt.Dimension(533, 220));
        java.awt.GridBagLayout jPanel4Layout1 = new java.awt.GridBagLayout();
        jPanel4Layout1.columnWidths = new int[]{0, 0, 0};
        jPanel4Layout1.rowHeights = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanel4.setLayout(jPanel4Layout1);

        sssNoLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        sssNoLabel.setText("SSS NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        jPanel4.add(sssNoLabel, gridBagConstraints);

        sssNoTextField.setEditable(false);
        sssNoTextField.setBackground(personalPanel.getBackground());
        sssNoTextField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        sssNoTextField.setBorder(null);
        sssNoTextField.setMinimumSize(new java.awt.Dimension(250, 20));
        sssNoTextField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 63, 5, 0);
        jPanel4.add(sssNoTextField, gridBagConstraints);

        philhealthNoLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        philhealthNoLabel.setText("PHILHEALTH NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        jPanel4.add(philhealthNoLabel, gridBagConstraints);

        philHealthNoTxtField.setEditable(false);
        philHealthNoTxtField.setBackground(personalPanel.getBackground());
        philHealthNoTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        philHealthNoTxtField.setBorder(null);
        philHealthNoTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        philHealthNoTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 63, 5, 0);
        jPanel4.add(philHealthNoTxtField, gridBagConstraints);

        pagibigNoLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        pagibigNoLabel.setText("PAGIBIG NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        jPanel4.add(pagibigNoLabel, gridBagConstraints);

        pagibigNoTxtField.setEditable(false);
        pagibigNoTxtField.setBackground(personalPanel.getBackground());
        pagibigNoTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        pagibigNoTxtField.setBorder(null);
        pagibigNoTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        pagibigNoTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 63, 5, 0);
        jPanel4.add(pagibigNoTxtField, gridBagConstraints);

        tinNoTxtField.setEditable(false);
        tinNoTxtField.setBackground(personalPanel.getBackground());
        tinNoTxtField.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        tinNoTxtField.setBorder(null);
        tinNoTxtField.setMinimumSize(new java.awt.Dimension(250, 20));
        tinNoTxtField.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 63, 5, 0);
        jPanel4.add(tinNoTxtField, gridBagConstraints);

        tinNoLabel.setFont(new java.awt.Font("Montserrat Medium", 1, 12)); // NOI18N
        tinNoLabel.setText("TIN NO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 0);
        jPanel4.add(tinNoLabel, gridBagConstraints);

        contributionIDsLabel.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        contributionIDsLabel.setText("Contribution ID's");
        contributionIDsLabel.setMinimumSize(new java.awt.Dimension(250, 25));
        contributionIDsLabel.setPreferredSize(new java.awt.Dimension(250, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        jPanel4.add(contributionIDsLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 18, 50);
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JLabel allowancesLabel;
    private javax.swing.JLabel basicSalaryLabel;
    private javax.swing.JTextField basicSalaryTxtField;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField birthdayTxtField;
    private javax.swing.JLabel clothingAllowanceLabel;
    private javax.swing.JTextField clothingAllowanceTxtField;
    private javax.swing.JLabel contributionIDsLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JTextField departmentTxtField;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JTextField empIDTxtField;
    private javax.swing.JPanel employmentPanel;
    private javax.swing.JLabel hourlyRateLabel;
    private javax.swing.JTextField hourlyRateTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JLabel pagibigNoLabel;
    private javax.swing.JTextField pagibigNoTxtField;
    private javax.swing.JLabel payLabel;
    private javax.swing.JLabel payLabel1;
    private javax.swing.JPanel payPanel;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JTextField philHealthNoTxtField;
    private javax.swing.JLabel philhealthNoLabel;
    private javax.swing.JLabel phoneAllowanceLabel;
    private javax.swing.JTextField phoneAllowanceTxtField;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JTextField phoneNoTxtField;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JTextField positionTxtField;
    private javax.swing.JLabel riceSubsidyLabel;
    private javax.swing.JTextField riceSubsidyTxtField;
    private javax.swing.JLabel semiMonthlyLabel;
    private javax.swing.JTextField semiMonthlyTxtField;
    private javax.swing.JLabel sssNoLabel;
    private javax.swing.JTextField sssNoTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTxtField;
    private javax.swing.JTextField supervisoTxtField;
    private javax.swing.JLabel supervisorLabel;
    private javax.swing.JLabel tinNoLabel;
    private javax.swing.JTextField tinNoTxtField;
    // End of variables declaration//GEN-END:variables
}
